services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_LDE
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '128M'

  nodejs:
    build: ./nodejs
    container_name : nodejs_LDE
    volumes:
      - ./www:/workspace
    working_dir: /workspace
    tty: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '256M'

  php:
    build: ./php
    container_name: php_LDE
    volumes:
      - ./www:/var/www/html
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '256M'

  perl:
    image: perl:stable
    container_name: perl_LDE
    volumes:
      - ./www:/workspace
    working_dir: /workspace
    tty: true
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '128M'

  mysql:
    image: mysql:8.0
    container_name: mysql_LDE
    environment:
      MYSQL_ROOT_PASSWORD: rooti01
      MYSQL_DATABSE: buildLDE
      MYSQL_USER: admin
      MYSQL_PASSWORD: admindb01
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: '256M'

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_LDE
    environment:
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: admindb01
    ports:
      - 8081:80
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '128M'

volumes:
  mysql_data:
